version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app  

  celery_worker:
    build: .
    command: celery -A app.core.celery_app worker --loglevel=info -Q pdf_worker
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/app

    volumes:
      - .:/app

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
